### PR TITLE
Fix incompatibility with Django>=1.11

### PR DESCRIPTION
**Pull request by commaster90**

### CODE REVIEW

**Comment by peterbe** [comment]
Does this work? I'm not using this project any more. Do you need me to make a release afterwards?

**Comment by commaster90** [comment]
Yes, it does work. I might as well refactor the _DatabaseFeatures_ and _DatabaseOperations_ class, so that I can pass in the classes like below, but the net result is the same.

```{py}
client_class = DatabaseClient
creation_class = DatabaseCreation
features_class = DatabaseFeatures
introspection_class = DatabaseIntrosepection
ops_class = DatabaseOperations
validation_class = BaseDatabaseValidation
```

It will be good to make a release so others can use it.

**Comment by peterbe** [comment]
Would you like me to add you as a contributor to this GitHub project so you can push and merge your own PRs? 
I can add you to the project's PyPI page too if you'd like.

**Comment by peterbe** [comment]
You've been invited now.

**Comment by commaster90** [comment]
Thanks for your invite. However, I worry that my passion might be temporary or short-lived.

**Pull request merged**
